### ISSUE TITLE
release and system logrotate rules result in file duplication

### ISSUE THREAD

**Issue by holgero** [cloudfoundry-incubator/routing-release#81] opened 2017-07-19 09:36 UTC
## Issue

The routing-release installs a cron job that runs logrotate on the files in `/var/vcap/sys/log/gorouter/*.log`. At the same time there is the system wide logrotate running on the same files. The later has been installed by the bosh-agent. Also both logrotates are configured slightly different: The logrotate run by this cron job has the flag `delaycompress` whereas the system wide logrotate does not use this flag.

Since the last stemcell update that introduces this [fix](https://bugs.launchpad.net/ubuntu/+source/logrotate/+bug/1630516) to logrotate this causes a problem:
The logrotate job of the routing-release leaves a file `access.log.1` in the monitored directory and the other logrotate job (configured through the bosh-agent) will copy that file to a file named `access.log.1-2017xxxxxx.backup` when it also does the rotation (this will happen if the `access.log` grew above the size threshold of 50MiB within the last 5 minutes). This file will remain in the directory and eventually the ephemeral disk of the VM will fill up. That in turn causes the router to halt.

## Context

routing-release installs a crontab job with this [gorouter_logrotate.cron.erb](https://github.com/cloudfoundry-incubator/routing-release/blob/8c82cbc0c90e3f8b0f8dc8e9d11b49fbc78e7673/jobs/gorouter/templates/gorouter_logrotate.cron.erb) and configures logrotate with this [logrotate.conf.erb](https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/gorouter/templates/logrotate.conf.erb).

Bosh-agent uses this [template](https://github.com/cloudfoundry/bosh-agent/blob/master/platform/linux_platform.go#L529) to setup logrotate for all logfiles of jobs.

Behavior of logrotate has been changed lately with this [change](https://github.com/logrotate/logrotate/pull/23/files).

## Steps to Reproduce

1. Deploy routing-release as it is used within cf-release v265 on stemcell 3421.11.
2. Switch on access log in the gorouter job
3. Create load on the deployed landscape in such a way that the `access.log` file grows by more than 50 MiB in 5 minutes.

## Expected result

No files named `*.backup` are created in `/var/vcap/sys/log/gorouter/` and the ephemeral disk does not fill up. The gorouter continues to work normally.

## Current result

In the directory `/var/vcap/sys/log/gorouter` files with names `*.backup` are being created every now and then.
And as soon as the ephemeral disk is full, the gorouter will answer requests with http status code 503.

## Possible Fix

Remove the installation the cron job and call to logrotate within this release.

## `name of issue` Output Results

Here is a screenshot showing the ephemeral disks of four router nodes filling up until I applied a workaround:
![diskusage](https://user-images.githubusercontent.com/359875/28360538-02a9538a-6c76-11e7-8904-408a40ad5921.png)

## Workaround

Configure routing-release in such a way that it doesn't do logrotation. That is set the property `properties.router.logrotate.size` to an insane big value, e.g.  `4G`.

**Comment by shalako** [comment] 2017-07-25 21:53
Thank you for reaching out. Because Gorouter generates more logs than other components, we need to check whether the size of the log file has reached the rotate threshold more frequently that the stemcell-provided rotate rule. We enable operators to tune the logrotate parameters with manifest properties:
  `router.logrotate.freq_min`
  `router.logrotate.rotate`
  `router.logrotate.size`

So the issue isn't necessarily that the release installs its own cron, but how to prevent file duplication. I'll update the title to reflect this, and we'll explore solutions.

**Comment by shashwathi** [comment] 2017-08-18 21:58
@holgero : 

I am unable to reproduce this issue on our test environment. This is what I have tried so far

1. Configure a vm with script that can send 200,000 requests with 10 parallel threads to gorouter.
1. Ran this script multiple times to generate access logs. 
1.  This is the file structure generated and I do not see any file duplication.

```
-rw-r--r-- 1 vcap vcap 181133219 Aug 18 20:35 access.log.1
-rw-r--r-- 1 vcap vcap  28395040 Aug 18 18:40 access.log.1-2017081818.backup
-rw-r--r-- 1 vcap vcap 181133250 Aug 18 19:10 access.log.1-2017081819.backup
-rw-r--r-- 1 vcap vcap  10321903 Aug 18 18:45 access.log.1.gz-2017081818.backup
-rw-r--r-- 1 vcap vcap  14783040 Aug 18 19:25 access.log.2.gz
-rw-r--r-- 1 vcap vcap  34790480 Aug 18 19:20 access.log.3.gz
-rw-r--r-- 1 vcap vcap  30633480 Aug 18 19:15 access.log.5.gz
-rw-r--r-- 1 vcap vcap  20293490 Aug 18 19:15 access.log.6.gz
-rw-r--r-- 1 vcap vcap  20303075 Aug 18 19:05 access.log.7.gz
```

Could you please provide what is the desired and current result are for file structure?

Regards
Shash

**Comment by Nino-K** [comment] 2017-08-23 18:51
@holgero:

We have managed to reproduce this issue. Looking into bosh logrotate template, currently bosh does not provide a way to configure the logrotate at granularity level which is required for this issue. Bosh team suggested a solution to move logrotation to `pre-start` script. 

Pros: 
- Eliminates the issue of having two(bosh&gorouter) logrotate tasks running simultaneously, which can solve this issue. 

Cons: 
- It affects the other jobs running on the vm. Since gorouter updates the bosh cron task, this affects the frequency of cron task for all process on gorouter vms.
- Metron agent does something very similar to gorouter in terms of configuring logrotate cron task and we are concerned that if they take `pre-start` approach, then there would be race condition among the 2 configurations. This requires co-ordination from loggregator team to agree on a workable solution.

Another short term solution would to eliminate the logrotate specified by the gorouter and rely on bosh logrotate as it is, however this will require to increase the size of ephemeral disk to 3x(or more if deployment is noisy) since the logrotate on bosh is 3x less frequent than gorouter. This solution is not really appealing for the following reasons: 
1. It seems to be quite expensive approach 
2. This will eliminate the operator's control over configuring logrotate more granularly [here](https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/gorouter/spec#L135-L143) 

Any thoughts? 

cc: @shalako @ahevenor

**Comment by holgero** [comment] 2017-08-29 14:07
> Another short term solution would to eliminate the logrotate specified by the gorouter and rely on bosh logrotate as it is

I agree, up to the **as it is**. In my opinion the solution should be that all deployments rely on bosh logrotate and that bosh logrotate covers all the needs of the deployments (via configuration or better defaults).

> It seems to be quite expensive approach

Hmm, compare this with regular disk overflows that lead to failing updates of the VMs ( /tmp is bind mounted to somewhere on the ephemeral disk and if processes can no longer write to /tmp, they just fail...). In the current situation the disk space needed to cover the situation is +Infinity.

> This will eliminate the operator's control over configuring logrotate

Yes that configurability seems to make sense. But does it make sense to have it only for the routing-release?

**Comment by rosenhouse** [comment] 2017-08-31 23:32
@holgero Suppose we provided a workaround:

- you could disable logging of access data to disk (e.g. by setting a new BOSH property on the `router` job)
- you would then [`enable_access_log_streaming`](https://github.com/cloudfoundry-incubator/routing-release/blob/b92ecab16e627e0811d5920f3fb3483092cfa60b/jobs/gorouter/spec#L228-L230) so that the access logs went to syslog.

What would you think about this approach?   It would seem to solve your immediate problem (disk filling).  But I'm curious if you'd miss the presence of that access log file on disk.  Or would you be satisfied to see the logs that you need via rsyslog forwarding or other syslog configuration?

**Comment by holgero** [comment] 2017-09-01 08:14
The files on disk are not very useful in this case anyway, because of the rapid filling and rotating.
The forwarded logs are far more important as they are be stored in a sufficiently large database.
So, yes, this approach looks promising to me.

**Comment by giner** [comment] 2017-11-17 01:59
> The files on disk are not very useful in this case anyway

I would not agree they are useless. While having long term storage for logs is important keeping latest logs locally help a lot while doing operations / development / testing.

**Comment by giner** [comment] 2017-11-17 05:03
We have just faced the same issue after stemcell upgrade. As a workaround we set very high threshold for logrotate.size: https://bosh.io/jobs/gorouter?source=github.com/cloudfoundry-incubator/cf-routing-release&version=0.166.0#p=router.logrotate.size.

**Comment by rosenhouse** [comment] 2017-11-17 05:16
Yes, the custom logrotate is now gone in v0.167.0.

Now routing-release relies only on BOSH logrotate, therefore this issue with `.backup` files should be resolved.  However, please be aware that BOSH's cron job runs less frequently and the logrotate rule allows the log files to grow somewhat larger before triggering a rotation.  Therefore, you may find you need a larger ephemeral disk to accommodate the increased log volume on your router VMs.

In addition an operator may opt to completely disable writing of access logs to disk by overriding the  new the `router.write_access_logs_locally` property on the `gorouter` job.

I think we can close this issue now.  Please comment if you have any feedback (positive or negative) on these most recent changes.

**Comment by giner** [comment] 2017-11-17 05:35
Latest stemcells run logrotate every 15 minutes (with threshold 50M for a log file size) which should be fine in most cases.

**Comment by holgero** [comment] 2017-11-17 07:20
Well, with "in this case" I meant in our case on our productive system. The local logfiles are rotated and deleted so fast that it just doesn't make any sense to even look at them to try to analyse a problem. I wasn't talking about other cases like development and testing.

Am 17. November 2017 02:59:29 MEZ schrieb Stanislav German-Evtushenko <notifications@github.com>:
>> The files on disk are not very useful in this case anyway
>
>I would not agree they are useless. While having long term storage for
>logs is important keeping latest logs locally help a lot while doing
>operations / development / testing.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cloudfoundry-incubator/routing-release/issues/81#issuecomment-345122512

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Closed** 2017-11-20 02:02 UTC
Labels: accepted
