### ISSUE TITLE
A problem with the acceptance tests

### ISSUE THREAD

**Issue by georgibarzev** [cloudfoundry-incubator/routing-release#64] opened 2017-02-01 16:12 UTC
Hi,

Is it possible to run the acceptance tests errand when the CF and Routing deployments are on AWS, not bosh-lite? I'm running routing release 0.143.0 and CF release 250 and the actual TCP routing works as expected, however the acceptance tests bosh errand fails with this:

```
• Failure [3.093 seconds]
Registration
/var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:86
  HTTP Route
  /var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:85
    can register, list, subscribe to sse and unregister routes [It]
    /var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:84

    Expected error:
        <*errors.errorString | 0xc4201d1060>: {
            s: "attempt to read from closed buffer",
        }
        attempt to read from closed buffer
    not to have occurred

Summarizing 1 Failure:

[Fail] Registration HTTP Route [It] can register, list, subscribe to sse and unregister routes
/var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:42

Ran 1 of 1 Specs in 3.098 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 0 Skipped
```

I've redacted the private details, the acceptance tests properties section in the manifest looks like this:

```
  acceptance_tests:
    addresses:
    ----
    cloud_controller:
      admin_password: ---
      admin_user: ---
      api: api.---
      apps_domain: ---
      use_http: false
    skip_ssl_validatio: true
    system_domain: ----
    include_http_routes: true
```

Any clues what I'm doing wrong? Thanks in advance.

Georgi

**Comment by shashwathi** [comment] 2017-02-01 16:56
Hi @georgibarzev : 
>Is it possible to run the acceptance tests errand when the CF and Routing deployments are on AWS, not bosh-lite? 

We do run acceptance tests against deployments on AWS in CI so I would expect it to work.

With regards to the error, I tried to reproduce it by passing wrong URL for UAA endpoint.
Sample integration config.
 
```
{
  "addresses": ["10.244.14.2"],
  "api": "api.bosh-lite.com",
  "admin_user": "admin",
  "admin_password": "admin",
  "skip_ssl_validation": true,
  "use_http":true,
  "apps_domain": "crapbosh-lite.com",
  "include_http_routes": true,
  "oauth": {
    "token_endpoint": "https://wronguaa.bosh-lite.com",
    "client_name": "tcp_emitter",
    "client_secret": "tcp-emitter-secret",
    "port": 443,
    "skip_ssl_validation": true
  }
}
```

Error 
```
• Failure [0.048 seconds]
Registration
/Users/pivotal/workspace/cf-release/src/routing-release/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:86
  HTTP Route
  /Users/pivotal/workspace/cf-release/src/routing-release/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:85
    can register, list, subscribe to sse and unregister routes [It]
    /Users/pivotal/workspace/cf-release/src/routing-release/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:84

    Expected error:
        <*errors.errorString | 0xc42019e050>: {
            s: "attempt to read from closed buffer",
        }
        attempt to read from closed buffer
    not to have occurred

    /Users/pivotal/workspace/cf-release/src/routing-release/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:42
```
There should be some logs present when the test failed. I am pasting the error log I received. 
```
{"timestamp":"1485968038.769961119","source":"rtr","message":"rtr.uaa-client.fetch-token-from-uaa-start","log_level":1,"data":{"endpoint":{"Scheme":"https","Opaque":"","User":null,"Host":"wronguaa.bosh-lite.com:443","Path":"/oauth/token","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"session":"3"}}
{"timestamp":"1485968038.802694082","source":"rtr","message":"rtr.uaa-client.fetch-token-from-uaa-end","log_level":1,"data":{"session":"3","status-code":404}}
{"timestamp":"1485968038.802751780","source":"rtr","message":"rtr.uaa-client.error-fetching-token","log_level":2,"data":{"error":"status code: 404, body: 404 Not Found: Requested route ('wronguaa.bosh-lite.com:443') does not exist.\n","session":"2"}}
streaming events failed: status code: 404, body: 404 Not Found: Requested route ('wronguaa.bosh-lite.com:443') does not exist
```

The logs clearly states the reason behind the failure. There is an option in manifest for run the tests in `verbose` mode. Could you try with that option and attach the sanitized logs here? 

Regards
Shash

**Comment by georgibarzev** [comment] 2017-02-01 17:41
Thanks for the quick reply. Seems like the problem is with the uaa certificate.

```
{"timestamp":"1485961853.583396912","source":"rtr","message":"rtr.uaa-client.fetch-token-from-uaa-start","log_level":1,"data":{"endpoint":{"Scheme":"https","Opaque":"", "User":null,"Host":"uaa.xxx.com:443","Path":"/oauth/token","RawPath":"","RawQuery":"","Fragment":""},"session":"3"}}
{"timestamp":"1485961853.620490074","source":"rtr","message":"rtr.uaa-client.error-fetching-token","log_level":2,"data":{"error":"Post https://uaa.xxx.com:443/oauth/token: x509: certificate signed by unknown authority","session":"2"}}
{"timestamp":"1485961854.121083021","source":"rtr","message":"rtr.uaa-client.fetch-token-from-uaa-start","log_level":1,"data":{"endpoint":{"Scheme":"https","Opaque":"", "User":null,"Host":"uaa.xxx.com:443","Path":"/oauth/token","RawPath":"","RawQuery":"","Fragment":""},"session":"4"}}
{"timestamp":"1485961854.127127409","source":"rtr","message":"rtr.uaa-client.error-fetching-token","log_level":2,"data":{"error":"Post https://uaa.xxx.com:443/oauth/token: x509: certificate signed by unknown authority","session":"2"}}
{"timestamp":"1485961854.627622843","source":"rtr","message":"rtr.uaa-client.fetch-token-from-uaa-start","log_level":1,"data":{"endpoint":{"Scheme":"https","Opaque":"", "User":null,"Host":"uaa.xxx.com:443","Path":"/oauth/token","RawPath":"","RawQuery":"","Fragment":""},"session":"5"}}
{"timestamp":"1485961854.633311033","source":"rtr","message":"rtr.uaa-client.error-fetching-token","log_level":2,"data":{"error":"Post https://uaa.xxx.com:443/oauth/token: x509: certificate signed by unknown authority","session":"2"}}
```

**Comment by shashwathi** [comment] 2017-02-01 21:32
Hi @georgibarzev : 

The certs should be signed by CA `uaa.service.internal_domain` (`cf.internal` is the default internal domain). Could you try updating the certs with that CA and run acceptance tests? 

Regards
Shash

**Comment by georgibarzev** [comment] 2017-02-02 11:01
Hi @shashwathi ,

Is it an issue that the certificates used by the uaa are self-signed? The internal domain is cf.internal as default, and there seems to be no problem when creating domains, routes and binding them to apps with the current routing and cf deployments. I assume the test failure itself is more of a warning from the test suite than a blocker? If so, is it possible to run the tests past this issue? Thanks.

Regards,
Georgi

**Comment by shashwathi** [comment] 2017-02-03 18:03
Hi @georgibarzev 

>  Is it an issue that the certificates used by the uaa are self-signed? 

It is not an issue. There is an option in the [manifest](https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/acceptance_tests/spec#L29) to allow self-signed certs. I can see from the sample manifest , this property is enabled.

>I assume the test failure itself is more of a warning from the test suite than a blocker? If so, is it possible to run the tests past this issue?

During the test suite, we actually use `uaa.system_domain.com` and all internal routing components use DNS(consul) entry `uaa.service.cf.internal`. This explains the difference of behavior you see during tests and running the commands yourself. I am very surprised that tests are validating the certs though. 

Can you set the property `include_http_routes` to `false`  and run the test suite. There are 2 test suites and we can disable one and see if the other works or not.

Regards
Shash

**Comment by georgibarzev** [comment] 2017-02-07 18:58
Hi @shashwathi ,

Setting `include_http_routes` to `false `gave longer response, however it seems the issue is the same:

```
Running Suite: HTTP Routes Suite
================================
Random Seed: 1486491955 - Will randomize all specs
Will run 1 of 1 specs

Running in parallel across 4 nodes

S [SKIPPING] in Spec Setup (BeforeEach) [0.000 seconds]
Registration [BeforeEach]
/var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:86
  HTTP Route
  /var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:85
    can register, list, subscribe to sse and unregister routes
    /var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/registration_test.go:84

    Skipping this test because Config.IncludeHttpRoutes is set to `false`.

    /var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/http_routes/http_routes_suite_test.go:50
------------------------------

Ran 0 of 1 Specs in 0.009 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 Pending | 1 Skipped

Ginkgo ran 1 suite in 4.689387975s
Test Suite Passed
Running Suite: TCP Routing
==========================
Random Seed: 1486491960 - Will randomize all specs
Will run 6 of 6 specs

Running in parallel across 4 nodes
{"timestamp":"1486491963.880917788","source":"test","message":"test.uaa-client.started-fetching-token","log_level":0,"data":{"endpoint":"https://uaa.xxx.com:443/oauth/token","force-update":true,"session":"2"}}
{"timestamp":"1486491963.881204128","source":"test","message":"test.uaa-client.fetch-token-from-uaa-start","log_level":1,"data":{"endpoint":{"Scheme":"https","Opaque":"
","User":null,"Host":"uaa.xxx.com:443","Path":"/oauth/token","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"session":"3"}}
{"timestamp":"1486491963.962223053","source":"test","message":"test.uaa-client.error-fetching-token","log_level":2,"data":{"error":"Post https://uaa.xxx.com:443/oauth/token: x509: certificate signed by unknown authority","session":"2"}}
{"timestamp":"1486491963.962257147","source":"test","message":"test.uaa-client.retry-fetching-token","log_level":0,"data":{"retry-count":0,"session":"2"}}
{"timestamp":"1486491964.462817907","source":"test","message":"test.uaa-client.fetch-token-from-uaa-start","log_level":1,"data":{"endpoint":{"Scheme":"https","Opaque":"
","User":null,"Host":"uaa.xxx.com:443","Path":"/oauth/token","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"session":"4"}}
{"timestamp":"1486491964.469788074","source":"test","message":"test.uaa-client.error-fetching-token","log_level":2,"data":{"error":"Post https://uaa.xxx.com:443/oauth/token: x509: certificate signed by unknown authority","session":"2"}}
{"timestamp":"1486491964.469820499","source":"test","message":"test.uaa-client.retry-fetching-token","log_level":0,"data":{"retry-count":1,"session":"2"}}
{"timestamp":"1486491964.970356226","source":"test","message":"test.uaa-client.fetch-token-from-uaa-start","log_level":1,"data":{"endpoint":{"Scheme":"https","Opaque":"
","User":null,"Host":"uaa.xxx.com:443","Path":"/oauth/token","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"session":"5"}}
{"timestamp":"1486491964.978094816","source":"test","message":"test.uaa-client.error-fetching-token","log_level":2,"data":{"error":"Post https://uaa.xxx.com:443/oauth/token: x509: certificate signed by unknown authority","session":"2"}}
{"timestamp":"1486491964.978131533","source":"test","message":"test.uaa-client.retry-fetching-token","log_level":0,"data":{"retry-count":2,"session":"2"}}
{"timestamp":"1486491965.478676558","source":"test","message":"test.uaa-client.fetch-token-from-uaa-start","log_level":1,"data":{"endpoint":{"Scheme":"https","Opaque":"
","User":null,"Host":"uaa.xxx.com:443","Path":"/oauth/token","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"session":"6"}}
{"timestamp":"1486491965.485564232","source":"test","message":"test.uaa-client.error-fetching-token","log_level":2,"data":{"error":"Post https://uaa.xxx.com:443/oauth/token: x509: certificate signed by unknown authority","session":"2"}}
```
The following 2 code lines are listed next to every failure, along with `expected error` blocks with cert errors ending in ` certificate signed by unknown authority not to have occurred`.
```
/var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/tcp_routing/tcp_routing_suite_test.go:90
/var/vcap/packages/acceptance_tests/src/code.cloudfoundry.org/routing-acceptance-tests/tcp_routing/tcp_routing_suite_test.go:118
```

The last section contains cf test failures like these:
```
[2017-02-07 18:26:06.14 (UTC)]> cf auth admin [REDACTED]
FAILED
No API endpoint set. Use 'cf login' or 'cf api' to target an endpoint.

[2017-02-07 18:26:06.48 (UTC)]> cf delete-user -f CATS-USER-3-2017_02_07-18h26m03.887s
FAILED
No API endpoint set. Use 'cf login' or 'cf api' to target an endpoint.

[2017-02-07 18:26:06.83 (UTC)]> cf logout
Logging out...
OK
```

Regards,
Georgi

**Comment by swetharepakula** [comment] 2017-02-07 19:22
Hi @georgibarzev,

The logs indicate when the tests try to create a uaa-client, the client notices the self-signed cert. However in acceptance tests if you have `skip_ssl_validation: true` you should not be seeing the error. If you are using the manifest you have above to set the acceptance test properties, there is a typo in `skip_ssl_validation` which may be the reason you are still encountering this issue.

If you are using the routing manifest to set up the acceptance tests, the only thing you need to change is 
```
acceptance_tests:
    ...
    skip_ssl_validation: true
    ...
```
from 
```
acceptance_tests:
    ...
    skip_ssl_validatio: true
    ...
```

Please let us know if that is not the problem.
Regards
@swetharepakula && @flawedmatrix 
The CF Routing Team

**Comment by georgibarzev** [comment] 2017-02-09 10:34
Hi @swetharepakula ,

Thanks for this, it was indeed the problem with the certification. 

I've just run the test suite again and the only remaining issue is with the following test case due to the password not being secure enough:

`cf create-user CATS-USER-3-2017_02_09-10h13m02.775s meow`

Is it possible to modify the password used for that test? I need it to use a password of at least 8 characters and it must contain at least 1 uppercase character, at least 1 digit and at least 1 special character.

Thanks again.

Regards,
Georgi

**Comment by shashwathi** [comment] 2017-02-09 17:30
@georgibarzev 
This feature currently exists in CATS(cf-acceptance-tests) but not in Routing acceptance tests.  

@shalako @abbyachau : There are CF installations which may have password policies and routing acceptance tests should provide the option to set the test password.

Regards
Shash

**Comment by shalako** [comment] 2017-02-09 21:06
We'll add property `acceptance_tests.user_password` to enable specifying the password for users created during the tests.

We'll also explore removing passwords from the logs, and generating a random password by default.

Prioritized.

**Comment by abbyachau** [comment] 2017-03-29 00:55
Hi @georgibarzev, we've implemented a new property to enable specifying the password for users during the tests. 

If you are running the tests using the [manifest](https://github.com/cloudfoundry-incubator/routing-release/blob/develop/jobs/acceptance_tests/spec), please set `acceptance_tests.user_password`. 

If you are running the tests manually, please review the instructions [here](https://github.com/cloudfoundry-incubator/routing-acceptance-tests) to set this property.

Please let us know us know if you have any feedback. Thanks!

**Comment by abbyachau** [comment] 2017-04-04 22:22
Hi @georgibarzev, thanks again for your feedback. We are closing this issue now - if you have any feedback regarding this new property, please do not hesitate to reopen this github issue. Thanks again!

**Closed** 2017-04-04 22:22 UTC
Labels: accepted
