### ISSUE TITLE
Garden-runc support

### ISSUE THREAD

**Issue by ablease** [cloudfoundry-incubator/routing-release#56] opened 2016-12-08 12:22 UTC
Hello, 

When deploying CF on bosh lite using garden-runc, we discovered a problem with the router job. 

```
/var/vcap/jobs/gorouter/bin/gorouter_ctl: line 35:
/proc/sys/net/ipv4/tcp_fin_timeout: No such file or directory
```
It seems the start script for the router is not detecting that it is running in the container and failing to write a proc file. The helper script to find out if you're running in a container [src/routing_utils/pidutils.sh](https://github.com/cloudfoundry-incubator/routing-release/blob/develop/src/routing_utils/pid_utils.sh#L123) exposes a function which doesn't support detecting garden-runc container names. 

This is what /proc/self/cgroups looks like in garden-linux
```
/:~$ cat /proc/self/cgroup
12:pids:/
11:hugetlb:/
10:net_prio:/
9:perf_event:/
8:net_cls:/
7:freezer:/
6:devices:/instance-3g3mjd8vjti
5:memory:/instance-3g3mjd8vjti
4:blkio:/
3:cpuacct:/instance-3g3mjd8vjti
2:cpu:/instance-3g3mjd8vjti
1:cpuset:/instance-3g3mjd8vjti
```

This is what /proc/self/cgroups looks like in garden-runc
```
/:~$ cat /proc/self/cgroup
12:pids:/c2014f15-e490-4124-75e4-e5b5a08ca89f
11:hugetlb:/c2014f15-e490-4124-75e4-e5b5a08ca89f
10:net_prio:/c2014f15-e490-4124-75e4-e5b5a08ca89f
9:perf_event:/c2014f15-e490-4124-75e4-e5b5a08ca89f
8:net_cls:/c2014f15-e490-4124-75e4-e5b5a08ca89f
7:freezer:/c2014f15-e490-4124-75e4-e5b5a08ca89f
6:devices:/c2014f15-e490-4124-75e4-e5b5a08ca89f
5:memory:/c2014f15-e490-4124-75e4-e5b5a08ca89f
4:blkio:/c2014f15-e490-4124-75e4-e5b5a08ca89f
3:cpuacct:/c2014f15-e490-4124-75e4-e5b5a08ca89f
2:cpu:/c2014f15-e490-4124-75e4-e5b5a08ca89f
1:cpuset:/c2014f15-e490-4124-75e4-e5b5a08ca89f
```

Is support for garden-runc on the roadmap for this release?

Regards

Alex and @Samze
CC: @teddyking

**Comment by shalako** [comment] 2016-12-08 18:00
Prioritized for eng review

**Comment by shashwathi** [comment] 2016-12-13 22:35
Hi @ablease: 

Thank you for raising this issue.
 
From my experience every containerization(eg: docker/warden) provides different ways to recognize it is a container. I do not have knowledge about garden-runc so it would take us some time to prioritize this but if this of any urgency we are happy to take a PR. 

Regards
Shash
CF Routing team

**Comment by markstgodard** [comment] 2016-12-14 00:41
Hi @ablease 

Are you working on converting bosh-lite to use `garden-runc` containers vs. `garden-linux` containers for CF deployments?

If so, this pattern of "running in container" detection, will likely affect more than just the `gorouter`

```sh
mark at evilcorp ~/workspace/cf-release $ ag "running_in_container\(\)" -A3
src/capi-release/src/capi_utils/container_utils.sh
3:running_in_container() {
4-  grep -q -E '/instance|/docker/' /proc/self/cgroup
5-}

src/common/utils.sh
86:running_in_container() {
87-  grep -q -E '/instance|/docker/' /proc/self/cgroup
88-}


src/loggregator/src/common/utils.sh
86:running_in_container() {
87-  grep -q '/instance' /proc/self/cgroup
88-}

src/nats-release/src/nats-common/utils.sh
90:running_in_container() {
91-  grep -q -E '/instance|/docker/' /proc/self/cgroup
92-}


src/postgres-release/src/postgres-common/utils.sh
80:running_in_container() {
81-  grep -q -E '/instance|/docker/' /proc/self/cgroup
82-}

src/routing-release/src/routing_utils/pid_utils.sh
123:running_in_container() {
124-  grep -q -E '/instance|/docker/' /proc/self/cgroup
125-}


mark at evilcorp ~/workspace/diego-release $ ag "running_in_container\(\)" -A3
src/pid_utils.sh
184:running_in_container() {
185-  grep -q -E '/instance|/docker/' /proc/self/cgroup
186-}
```

cc @shashwathi

**Comment by markstgodard** [comment] 2016-12-14 01:12
Odd, I have garden-runc 1.0.4 and if I create a container `/proc/self/cgroup` does seem to have the `instance-` prefix.. 

Maybe the garden team can clarify.

```sh
mark at evilcorp ~ $ gaol -t 10.244.16.14:7777 create -n foo
foo
mark at evilcorp ~ $ gaol -t 10.244.16.14:7777 run --attach foo -c "cat /proc/self/cgroup" | grep -q -E "/instance|/docker"
mark at evilcorp ~ $ echo $?
0
mark at evilcorp ~ $ gaol -t 10.244.16.14:7777 run --attach foo -c "cat /proc/self/cgroup"
12:hugetlb:/foo
11:net_prio:/foo
10:perf_event:/foo
9:net_cls:/foo
8:freezer:/foo
7:devices:/instance-3v1t31b79a3/foo
6:memory:/instance-3v1t31b79a3/foo
5:blkio:/foo
4:cpuacct:/instance-3v1t31b79a3/foo
3:cpu:/instance-3v1t31b79a3/foo
2:cpuset:/instance-3v1t31b79a3/foo
1:name=systemd:/
```

**Comment by shalako** [comment] 2016-12-14 02:11
@ablease echoing @markstgodard 's comment, could you please provide us with context as to why you are attempting to run Gorouter in garden-runc?

Thank you

**Comment by shashwathi** [comment] 2016-12-14 02:14
Like @markstgodard  mentioned earlier Diego and lot of other release within CF use the similar function to detect whether it is running in container. I will be surprised if`gorouter` is the only component which fails to run in `garden-runc`. 

Regards
Shash

**Comment by ablease** [comment] 2016-12-14 11:26
To address @markstgodard's and @shalako comment about the context. We were creating a brand new CF deployment on bosh-lite using garden-runc. We previously did this using garden linux and our assumption is that we should be able to use garden-runc.

Thanks to @teddyking we realized that actually, bosh lite [does not support garden runc](https://github.com/cloudfoundry/bosh-lite/blob/d916aecb0d8fe8a9f8a23e641696504442a9c3fe/packer/templates/bosh_lite_manifest_template.yml#L11) at the moment!  Our bad on that one :) 

However the problem still stands that the current `running_in_container` function may break when bosh-lite versions, backed by garden-runc are out there.

Currently the garden team detect if they are running in a container using a [different method](https://github.com/cloudfoundry/garden-runc-release/blob/develop/ci/scripts/aufs#L8). Perhaps @teddyking can shed light on a better approach. 

For the releases that @markstgodard posted, yes they may contain the `running_in_container` function, but for example in the loggregator or nats releases, the function is never actually called. **https://github.com/cloudfoundry/loggregator/search?utf8=%E2%9C%93&q=running_in_container**

We appreciate that this isn't limited to a routing release issue so thanks for taking the time to look into it.

Cheers,
Alex and @Samze

**Comment by shalako** [comment] 2016-12-14 18:42
Hello @ablease,

I'm assuming this isn't a default BOSH Lite configuration, or we would have run into it. 

We can't prioritize this now as we have more urgent commitments, but as @shashwathi mentioned we would welcome a PR.

Best,
Shannon

**Comment by RochesterinNYC** [comment] 2016-12-16 16:36
The Buildpacks team recently ran into this as well when we were trying to switch our BOSH Lites over from garden-linux to garden-runc.

We are hoping that this will make running CATS against CF + Diego deployed to these BOSH Lites more reliable on GCP (we're currently encountering a lot of flakiness in tests and this is a problem for open source CF component teams looking to migrate their CI + BOSH Lites to GCP).

**Comment by shashwathi** [comment] 2016-12-16 19:42
@RochesterinNYC  @ablease : 
There are couple of things to note based on your comment
- Currently there is no support for running CF on bosh lite using garden-runc. 
The usual way to run bosh lite would be using vagrant which explains why we have not run into this issue on our CI. Typically we use bosh-lite as a dev/testing tool. What are you using bosh-lite for? This can help us understand your use case for running bosh-lite and wanting to use garden-runc vs. garden-linux.  Thanks for providing the blog post, that gives us a better understanding of what you are attempting. Another question we have is what versions of releases (cf-release, bosh-lite repo, bosh-lite stemcell) are you using?
- Another thing to note is that network flakiness is known to occur in GCP.
  This issue is being addressed by Release Integration team( https://github.com/cloudfoundry/cf-deployment/issues/27 )

cc @dsabeti 

Regards
Shash && @swetharepakula

**Comment by RochesterinNYC** [comment] 2016-12-16 20:39
@shashwathi Sure, we're the Cloud Foundry buildpacks team and in our CI, our buildpack test suites must run against LTS and Edge CF versions. LTS is using the following [versions](https://github.com/cloudfoundry/buildpacks-ci/blob/master/config/bosh-lite/lts-1-gcp.yml):

```
cf-version: 225
diego-version: 0.1441.0
garden-linux-version: 0.327.0
etcd-version: 18
```

Edge is using the latest releases from the last released version of cf-release, so:
```
cf-version: 249
diego-version: 1.2.0
garden-runc-version: 1.0.4
cflinuxfs2-rootfs-version: 1.41.0
```

We use the latest version (commit) of the bosh-lite repo for generating the cf and diego manifests and use `3312.9` of BOSH Lite warden.

We're having issues with getting CATS to pass on BOSH Lites on GCP that are running the edge versions. Network issues might be one cause, but we're also seeing unusually high disk usage on the BOSH Lites (~25% CPU wait caused by waiting for IO). We were hoping that switching from garden-linux to garden-runc for the BOSH Lites would cause some improvement here.

**Comment by shashwathi** [comment] 2017-01-09 20:41
@RochesterinNYC : 

 Thank you for taking to time to answer my questions in detail and I apologize for delayed reply.

We could try to adopt the equivalent function of [`running_in_container`](https://github.com/cloudfoundry/garden-runc-release/blob/develop/ci/scripts/aufs#L8) function from `garden-runc-release` to verify this fix works.

Regards
Shash

**Comment by swetharepakula** [comment] 2017-01-26 18:20
Closing issue.

**Closed by swetharepakula** 2017-01-26 18:20 UTC
Labels: accepted

**Comment by drnic** [comment] 2017-02-09 00:57
I saw this issue today on CF v235 on bosh-lite running bosh/260.3 & garden-runc/1.0.0 (which is the latest garden-runc http://bosh.io/releases/github.com/cloudfoundry-incubator/garden-runc-release?all=1)

Is this issue closed because there is a fix on garden-runc edge? Or is there a workaround/fix I can apply to my bosh-lite?

**Comment by shashwathi** [comment] 2017-02-09 01:04
@drnic. 

The fix is in the most recent Routing Release v0.144.0. It should be in the next CF Release.
There is no workaround for older versions. The change is in on our control scripts (https://github.com/cloudfoundry-incubator/routing-release/commit/e8bfa3b78e9f02f1990a7dbcbde38c8896fde33b). You would have to manually make this change for it to work on CF v235.

**Comment by ematpl** [comment] 2017-02-09 01:09
Also, @drnic, garden-runc-release has moved to the cloudfoundry org, so check https://bosh.io/releases/github.com/cloudfoundry/garden-runc-release?all=1 instead.

**Comment by drnic** [comment] 2017-02-09 01:10
@shashwathi  my old v235 deployment didn't include an explicit routing-release usage (it has been working fine so I just keep using it for integration testing). If v235 keeps failing after upgrading bosh-lite's garden-runc, I'll abandon it and deploy newer cf.

**Comment by ematpl** [comment] 2017-02-09 01:12
@drnic you'll have the same problem with GRR 1.1.1, since it uses the same cgroups hierarchy.

**Comment by drnic** [comment] 2017-02-09 05:45
Ok, replacing cf-250's router with explicit routing-release v0.144 works, thanks.
